module.exports = {
  ROLES: {
    ADMIN: "ADMIN",
    TELLER: "TELLER",
    LOAN_OFFICER: "LOAN_OFFICER",
    MANAGER: "MANAGER",
  },

  USER_STATUS: {
    ACTIVE: "ACTIVE",
    LOCKED: "LOCKED",
  },

  GENDER: {
    MALE: "MALE",
    FEMALE: "FEMALE",
    OTHER: "OTHER",
  },

  SAVING_STATUS: {
    ACTIVE: "ACTIVE",
    CLOSED: "CLOSED",
    MATURED: "MATURED",
  },

  SAVING_TYPE: {
    NO_TERM: "NO_TERM", // không kỳ hạn
    TERM_1M: "TERM_1M",
    TERM_3M: "TERM_3M",
    TERM_6M: "TERM_6M",
    TERM_12M: "TERM_12M",
    TERM_24M: "TERM_24M",
  },

  SAVING_TERM_MONTHS: {
    NO_TERM: 0,
    TERM_1M: 1,
    TERM_3M: 3,
    TERM_6M: 6,
    TERM_12M: 12,
    TERM_24M: 24,
  },

  LOAN_STATUS: {
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    DISBURSED: "DISBURSED",
    OVERDUE: "OVERDUE",
    SETTLED: "SETTLED",
  },

  LOAN_TYPE: {
    PERSONAL: "PERSONAL",
    BUSINESS: "BUSINESS",
    MORTGAGE: "MORTGAGE",
    AUTO: "AUTO",
    EDUCATION: "EDUCATION",
  },

  TRANSACTION_TYPE: {
    DEPOSIT: "DEPOSIT",
    WITHDRAW: "WITHDRAW",
    SAVING_CLOSE: "SAVING_CLOSE",
    LOAN_DISBURSEMENT: "LOAN_DISBURSEMENT",
    LOAN_REPAYMENT: "LOAN_REPAYMENT",
  },

  NOTIFICATION_TYPE: {
    LOAN_OVERDUE: "LOAN_OVERDUE",
    LOAN_APPROVED: "LOAN_APPROVED",
    LOAN_REJECTED: "LOAN_REJECTED",
    SAVING_MATURED: "SAVING_MATURED",
    SYSTEM: "SYSTEM",
    ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  },

  AUDIT_ACTION: {
    LOGIN: "LOGIN",
    LOGIN_FAILED: "LOGIN_FAILED",
    LOGOUT: "LOGOUT",
    DEPOSIT: "DEPOSIT",
    WITHDRAW: "WITHDRAW",
    OPEN_SAVING: "OPEN_SAVING",
    CLOSE_SAVING: "CLOSE_SAVING",
    LOAN_APPLY: "LOAN_APPLY",
    LOAN_APPROVE: "LOAN_APPROVE",
    LOAN_REJECT: "LOAN_REJECT",
    LOAN_DISBURSE: "LOAN_DISBURSE",
    LOAN_REPAYMENT: "LOAN_REPAYMENT",
    USER_CREATE: "USER_CREATE",
    USER_UPDATE: "USER_UPDATE",
    USER_DELETE: "USER_DELETE",
    USER_LOCK: "USER_LOCK",
    USER_UNLOCK: "USER_UNLOCK",
    PASSWORD_CHANGE: "PASSWORD_CHANGE",
    PASSWORD_RESET: "PASSWORD_RESET",
    CUSTOMER_CREATE: "CUSTOMER_CREATE",
    CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
    CUSTOMER_DELETE: "CUSTOMER_DELETE",
    CONFIG_UPDATE: "CONFIG_UPDATE",
    INTEREST_RATE_UPDATE: "INTEREST_RATE_UPDATE",
  },
};
